# Generated by Django 3.2.9 on 2022-03-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_order_ordered_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderid',
        ),
    ]
